### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/dyalog-jupyter-notebooks#11]
https://render.githubusercontent.com/view/ipynb?commit=8cbcf0fdba9d2e994dfc70eefd485458f5c7b263&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4479616c6f672f6479616c6f672d6a7570797465722d6e6f7465626f6f6b732f386362636630666462613964326539393464666337306565666434383534353866356337623236332f52616e6b253230616e6425323044657074682e6970796e62&nwo=Dyalog%2Fdyalog-jupyter-notebooks&path=Rank+and+Depth.ipynb&repository_id=138751474&repository_type=Repository#Enlcose

You can see it even in the link: "Enlcose" instead of "Enclose".
Good stuff, by the way!
The formatting of the output, at least in the github viewer, is suboptimal, though. In some cases, like the explanation of the monadic unique on matrices, it's confusing, since the matrix is flattened into what appears to be a vector...

![image](https://user-images.githubusercontent.com/2143482/47151348-c20a6f00-d2d9-11e8-9730-50efd4bd3f04.png)

**Comment by abrudz** [comment]
I doubt we can do anything on our side about GitHub rendering wrong. Project Jupyter's *nbviewer* gets it right:
![image](https://user-images.githubusercontent.com/10961427/47151815-b2d3f300-d2d2-11e8-9985-eca199ea5dc7.png)
